# Generated by Django 5.2 on 2025-04-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
