# Generated by Django 5.2 on 2025-04-27 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
