# Generated by Django 5.2 on 2025-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_adhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
