# Generated by Django 5.2 on 2025-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_adstatus_description_en_adstatus_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
