# Generated by Django 5.2 on 2025-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_ad_city_en_ad_city_ru_ad_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык объявления'),
        ),
    ]
