# Generated by Django 5.2 on 2025-06-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_ad_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='adstatus',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
