# Generated by Django 5.2 on 2025-06-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_ad_city_en_remove_ad_city_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adstatus',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adstatus',
            name='name_kk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
