# Generated by Django 5.2 on 2025-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_adstatus_description_kk_adstatus_name_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык объявления'),
        ),
    ]
